### ISSUE TITLE
Source of Data?

### ISSUE THREAD

**Issue by devdattaT** [justinelliotmeyers/INDIA_RANDOM_DATA_DUMP#1]
Hi Justin!

What is the source of this data?
I have found that the name of the towns, as well as the geometries are quite strange. For example, here is the data overlayed over OSM, in the Pune Region.

![image](https://user-images.githubusercontent.com/4159622/164611596-565c6309-3d21-47d5-b4bb-37b26b12c4c2.png)

**Comment by justinelliotmeyers** [comment]
@devdattaT Hey! I no longer have access to the machine I used to ingest this info. I'll see if I can find it online again and update you ASAP.

Yes, the data is very unique in some urban areas - or just any location in general. Some are spot on 100% correct - some are... wrong, but the data came from something official. What that something is I will lyk. Talk soon! Justin

**Comment by justinelliotmeyers** [comment]
Devdatta, I don't have the exact page saved out. I'll send you what I have offline in a DM. Thanks!
Justin
